[SQUASH]sm8150-common: Add denials for opcam
sm8150-common: sepolicy: correct some denials

W HwBinder:845_2: type=1400 audit(0.0:250): avc: denied { read } for name="input" dev="tmpfs" ino=31508 scontext=u:r:hal_camera_default:s0 tcontext=u:object_r:input_device:s0 tclass=dir permissive=0

W com.oneplus.camera: type=1400 audit(0.0:256): avc: denied { read } for comm=5363656E6520636C61737369666965 name="adsprpc-smd-secure" dev="tmpfs" ino=31648 scontext=u:r:priv_app:s0:c512,c768 tcontext=u:object_r:vendor_xdsp_device:s0 tclass=chr_file permissive=0 app=com.oneplus.camera

W com.oneplus.camera: type=1400 audit(0.0:252): avc: denied { read } for comm=446576696365207374617465206D61 name="temp" dev="sysfs" ino=80529 scontext=u:r:priv_app:s0:c512,c768 tcontext=u:object_r:vendor_sysfs_battery_supply:s0 tclass=file permissive=0 app=com.oneplus.camera

Signed-off-by: Pranav <npv12@iitbbs.ac.in>

sm8150-common: sepolicy: allow camera to read /dev/adsprpc-smd-secure

* fixes portrait mode in oneplus camera
`05-20 17:02:33.677   878  1598 E OPRTB   : doLoadLibrary():1542 doLoadLibrary RTB select: /vendor/lib64/libarcsoft_dualcam_bokeh_api.so, bokeh_select:0
05-20 17:02:33.678   878  1598 E android.hardware.camera.provider@2.4-service_64: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:2459: Error -1: apps_dev_init: app does not have access to fastrpc device of domain 3 (Permission denied)
05-20 17:02:33.678   878  1598 E android.hardware.camera.provider@2.4-service_64: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:2588: Error 0xffffffff: apps_dev_init failed for domain 3, errno Permission denied
05-20 17:02:33.672   878   878 W provider@2.4-se: type=1400 audit(0.0:55): avc: denied { read } for name="adsprpc-smd-secure" dev="tmpfs" ino=28876 scontext=u:r:hal_camera_default:s0 tcontext=u:object_r:vendor_xdsp_device:s0 tclass=chr_file permissive=0`

Signed-off-by: Omkar Chandorkar <gotenksIN@aosip.dev>
Signed-off-by: Pranav <npv12@iitbbs.ac.in>

sm8150-common: more sepolicy fun

Signed-off-by: Pranav <npv12@iitbbs.ac.in>

sm8150-common: sepolicy: Let oneplus camera have its own domain

* This can separate sepolicy for this specific app.

Change-Id: Iba7f2271ce853f69c230970e0916599cc3551b42
Signed-off-by: Pranav <npv12@iitbbs.ac.in>

sm8150-common: Resolve some oneplus camera related denials

Signed-off-by: Pranav <npv12@iitbbs.ac.in>

sm8150-common: Resolve some camera denials

Signed-off-by: Pranav <npv12@iitbbs.ac.in>

sm8150-common: sepolicy: Fix denials for some apps

Signed-off-by: Pranav <npv12@iitbbs.ac.in>

sm8150-common: And another camera denials

Co-authored-by: Vaisakh Murali <mvaisakh@statixos.com>
Co-authored-by: Hikari-no-Tenshi <kyryljan.serhij@gmail.com>
Co-authored-by: Lup Gabriel <gwolf2u.website@gmail.com>
Signed-off-by: Pranav <npv12@iitbbs.ac.in>